version: '3'
services:
  web:
    restart: always
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Docker/Config:/Config/
      - ./Docker/Config/php.ini:/usr/local/etc/php/php.ini
      - ./Docker/Config/ProjectFiles:/var/www/html/
